//go:build ignore

// gen-runconfig-docs parses types/runconfig.go and emits
// types/runconfig_docs.go — a generated lookup table that backs the
// `stirrup config explain` subcommand.
//
// The lookup is generated rather than computed at runtime so:
//
//   - The harness binary does not depend on go/ast (an entire compiler
//     toolchain) at runtime. The lookup is a plain map literal.
//   - Operators reading the source can `cat types/runconfig_docs.go`
//     and see every doc string the explain command will surface — no
//     hidden parsing step.
//   - CI catches drift: `just verify-docs` regenerates and fails on
//     diff, the same pattern as `just proto`.
//
// Scope: this driver walks the struct types declared in
// types/runconfig.go. The parsing heuristics live in
// types/internal/docsgen so `go test ./types/...` can cover them;
// this file is a thin driver that wires the package up to the
// runconfig.go source and writes the formatted Go literal.
//
// Invocation: `go run scripts/gen-runconfig-docs.go` from the repo
// root. The `//go:generate` directive in types/runconfig.go points at
// this file, so `go generate ./types/...` also works.

package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"github.com/rxbynerd/stirrup/types/docsgen"
)

func main() {
	src, out, err := resolvePaths()
	if err != nil {
		fail(err)
	}

	file, _, err := docsgen.ParseFile(src)
	if err != nil {
		fail(err)
	}

	ins := docsgen.NewInspector()
	ins.Collect(file)

	root, ok := ins.Structs["RunConfig"]
	if !ok {
		fail(fmt.Errorf("RunConfig struct not found in %s", src))
	}

	docs := map[string]*docsgen.FieldDoc{}
	docs[""] = ins.RootDoc(root)
	ins.Walk(root, "", "RunConfig", docs, map[string]bool{"RunConfig": true})

	if err := emitFile(out, docs); err != nil {
		fail(err)
	}
}

func resolvePaths() (src, out string, err error) {
	// Two supported entry points:
	//   1. Repo root: ./types/runconfig.go and ./types/runconfig_docs.go.
	//   2. ./types (when invoked via go generate): runconfig.go in pwd.
	wd, err := os.Getwd()
	if err != nil {
		return "", "", err
	}
	candidates := [][2]string{
		{filepath.Join(wd, "types", "runconfig.go"), filepath.Join(wd, "types", "runconfig_docs.go")},
		{filepath.Join(wd, "runconfig.go"), filepath.Join(wd, "runconfig_docs.go")},
	}
	for _, c := range candidates {
		if _, statErr := os.Stat(c[0]); statErr == nil {
			return c[0], c[1], nil
		}
	}
	return "", "", fmt.Errorf("runconfig.go not found relative to %s", wd)
}

// emitFile renders the lookup table to disk.
func emitFile(path string, docs map[string]*docsgen.FieldDoc) error {
	var buf bytes.Buffer
	buf.WriteString(`// Code generated by scripts/gen-runconfig-docs.go. DO NOT EDIT.
//
// This file backs the ` + "`stirrup config explain`" + ` subcommand. Run
// ` + "`just gen-docs`" + ` to regenerate after editing runconfig.go doc
// comments. ` + "`just verify-docs`" + ` checks the file is up to date in CI.

package types

// FieldDoc carries the surfaced documentation for one RunConfig field
// path. The shape is intentionally flat so the explain command can
// emit it as JSON without further transformation.
type FieldDoc struct {
	Path        string   ` + "`json:\"path\"`" + `
	Name        string   ` + "`json:\"name\"`" + `
	Type        string   ` + "`json:\"type\"`" + `
	JSONTag     string   ` + "`json:\"jsonTag\"`" + `
	Doc         string   ` + "`json:\"doc\"`" + `
	Default     string   ` + "`json:\"default,omitempty\"`" + `
	Enum        []string ` + "`json:\"enum,omitempty\"`" + `
	Children    []string ` + "`json:\"children,omitempty\"`" + `
	Kind        string   ` + "`json:\"kind\"`" + `
	Optional    bool     ` + "`json:\"optional,omitempty\"`" + `
	ParentPath  string   ` + "`json:\"parentPath,omitempty\"`" + `
	OwnerStruct string   ` + "`json:\"ownerStruct,omitempty\"`" + `
}

// FieldDocs maps a dot-separated field path on RunConfig to the
// surfaced documentation entry. The empty string maps to the
// top-level RunConfig overview.
//
// Map-valued fields contribute a synthetic ` + "`<key>`" + ` segment
// (e.g. ` + "`providers.<name>.type`" + `) so an operator can ask about
// the per-entry shape. Slice-valued struct fields use ` + "`[]`" + `
// instead (` + "`tools.mcpServers.[].uri`" + `).
var FieldDocs = map[string]FieldDoc{
`)

	keys := make([]string, 0, len(docs))
	for k := range docs {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		fd := docs[k]
		fmt.Fprintf(&buf, "\t%s: {\n", strconv.Quote(k))
		fmt.Fprintf(&buf, "\t\tPath:        %s,\n", strconv.Quote(fd.Path))
		fmt.Fprintf(&buf, "\t\tName:        %s,\n", strconv.Quote(fd.Name))
		fmt.Fprintf(&buf, "\t\tType:        %s,\n", strconv.Quote(fd.Type))
		fmt.Fprintf(&buf, "\t\tJSONTag:     %s,\n", strconv.Quote(fd.JSONTag))
		fmt.Fprintf(&buf, "\t\tDoc:         %s,\n", strconv.Quote(fd.Doc))
		if fd.Default != "" {
			fmt.Fprintf(&buf, "\t\tDefault:     %s,\n", strconv.Quote(fd.Default))
		}
		if len(fd.Enum) > 0 {
			fmt.Fprintf(&buf, "\t\tEnum:        %s,\n", quoteSlice(fd.Enum))
		}
		if len(fd.Children) > 0 {
			fmt.Fprintf(&buf, "\t\tChildren:    %s,\n", quoteSlice(fd.Children))
		}
		fmt.Fprintf(&buf, "\t\tKind:        %s,\n", strconv.Quote(fd.Kind))
		if fd.Optional {
			fmt.Fprintf(&buf, "\t\tOptional:    true,\n")
		}
		if fd.ParentPath != "" {
			fmt.Fprintf(&buf, "\t\tParentPath:  %s,\n", strconv.Quote(fd.ParentPath))
		}
		if fd.OwnerStruct != "" {
			fmt.Fprintf(&buf, "\t\tOwnerStruct: %s,\n", strconv.Quote(fd.OwnerStruct))
		}
		buf.WriteString("\t},\n")
	}
	buf.WriteString("}\n")

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		// Write unformatted output for debugging.
		_ = os.WriteFile(path+".unformatted", buf.Bytes(), 0o644)
		return fmt.Errorf("format generated source: %w", err)
	}
	if err := os.WriteFile(path, formatted, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	return nil
}

func quoteSlice(ss []string) string {
	var b strings.Builder
	b.WriteString("[]string{")
	for i, s := range ss {
		if i > 0 {
			b.WriteString(", ")
		}
		b.WriteString(strconv.Quote(s))
	}
	b.WriteByte('}')
	return b.String()
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, "gen-runconfig-docs:", err)
	os.Exit(1)
}
